server:
  port: 8199
#  port: 80

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

upload:
  picture:
        path=F:\project\Test\chat:
#    path=/data/tomcat/deploy/image:

spring:
  datasource:
    name: mydata  #库名？
    url: jdbc:mysql://27.102.132.130:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8 #数据库地址
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8 #数据库地址
    username: root  #用户名
    password: 123456 #密码
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource  #阿里驱动
    driver-class-name: com.mysql.jdbc.Driver

    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    # redis的配置
    redis:
      database: 1
#      host: 127.0.0.1
      host: 27.102.132.130
      port: 6379
      timeout: 5000ms #超时毫秒
      password: # 密码，如果没有的话，不用输入
      jedis:
        pool:
          max-wait: -1 #阻塞最大时间
          max-idle: 8 #最大空闲的链接
          min-idle: 0 #最小空闲的链接
          max-active: 8 #最大链接数量

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entiy


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
